# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = Debug/openjaus-mobility
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-mobility.so
  DEFINES   += -DDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = Release/openjaus-mobility
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-mobility.so
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/GlobalPathSegmentDriver.o \
	$(OBJDIR)/LocalWaypointDriver.o \
	$(OBJDIR)/LocalPathSegmentDriver.o \
	$(OBJDIR)/PrimitiveDriver.o \
	$(OBJDIR)/VelocityStateDriver.o \
	$(OBJDIR)/LocalWaypointListDriver.o \
	$(OBJDIR)/GlobalWaypointListDriver.o \
	$(OBJDIR)/AccelerationStateSensor.o \
	$(OBJDIR)/VelocityStateSensor.o \
	$(OBJDIR)/LocalPoseSensor.o \
	$(OBJDIR)/LocalVectorDriver.o \
	$(OBJDIR)/GlobalWaypointDriver.o \
	$(OBJDIR)/GlobalVectorDriver.o \
	$(OBJDIR)/GlobalPoseSensor.o \
	$(OBJDIR)/ListManaged.o \
	$(OBJDIR)/GlobalVectorReadyLoop.o \
	$(OBJDIR)/LocalPoseControlledLoop.o \
	$(OBJDIR)/LwldControlledLoop.o \
	$(OBJDIR)/GposDefaultLoop.o \
	$(OBJDIR)/VelocityStateDefaultLoop.o \
	$(OBJDIR)/LwldDefaultLoop.o \
	$(OBJDIR)/GlobalVectorDefaultLoop.o \
	$(OBJDIR)/GposControlledLoop.o \
	$(OBJDIR)/GwdControlledLoop.o \
	$(OBJDIR)/LpsdReadyLoop.o \
	$(OBJDIR)/GwldControlledLoop.o \
	$(OBJDIR)/VsdDefaultLoop.o \
	$(OBJDIR)/GwdReadyLoop.o \
	$(OBJDIR)/GwldDefaultLoop.o \
	$(OBJDIR)/LpsdControlledLoop.o \
	$(OBJDIR)/LocalPoseDefaultLoop.o \
	$(OBJDIR)/GwdDefaultLoop.o \
	$(OBJDIR)/LpsdDefaultLoop.o \
	$(OBJDIR)/PrimitiveDriverReadyLoop.o \
	$(OBJDIR)/AccelerationStateDefaultLoop.o \
	$(OBJDIR)/VsdControlledLoop.o \
	$(OBJDIR)/LwdDefaultLoop.o \
	$(OBJDIR)/LwdControlledLoop.o \
	$(OBJDIR)/ListManagerDefaultLoop.o \
	$(OBJDIR)/GpsdReadyLoop.o \
	$(OBJDIR)/PrimitiveDriverDefaultLoop.o \
	$(OBJDIR)/VsdReadyLoop.o \
	$(OBJDIR)/LocalVectorReadyLoop.o \
	$(OBJDIR)/GpsdControlledLoop.o \
	$(OBJDIR)/GpsdDefaultLoop.o \
	$(OBJDIR)/LwldReadyLoop.o \
	$(OBJDIR)/LwdReadyLoop.o \
	$(OBJDIR)/ListManagerControlledLoop.o \
	$(OBJDIR)/GwldReadyLoop.o \
	$(OBJDIR)/LocalVectorDefaultLoop.o \
	$(OBJDIR)/QueryActiveElement.o \
	$(OBJDIR)/SetLocalPose.o \
	$(OBJDIR)/SetGeomagneticProperty.o \
	$(OBJDIR)/ReportElementList.o \
	$(OBJDIR)/ReportAccelerationState.o \
	$(OBJDIR)/QueryVelocityCommand.o \
	$(OBJDIR)/SetGlobalPose.o \
	$(OBJDIR)/ReportGlobalPose.o \
	$(OBJDIR)/QueryVelocityState.o \
	$(OBJDIR)/SetAccelerationLimit.o \
	$(OBJDIR)/SetLocalWaypoint.o \
	$(OBJDIR)/ReportLocalPose.o \
	$(OBJDIR)/QueryLocalVector.o \
	$(OBJDIR)/ReportActiveElement.o \
	$(OBJDIR)/ConfirmElementRequest.o \
	$(OBJDIR)/QueryElement.o \
	$(OBJDIR)/ReportElement.o \
	$(OBJDIR)/QueryGlobalPose.o \
	$(OBJDIR)/ReportVelocityState.o \
	$(OBJDIR)/SetTravelSpeed.o \
	$(OBJDIR)/ReportGlobalPathSegment.o \
	$(OBJDIR)/QueryElementCount.o \
	$(OBJDIR)/ReportAccelerationLimit.o \
	$(OBJDIR)/ReportTravelSpeed.o \
	$(OBJDIR)/ReportVelocityCommand.o \
	$(OBJDIR)/QueryTravelSpeed.o \
	$(OBJDIR)/ReportGlobalVector.o \
	$(OBJDIR)/QueryGlobalPathSegment.o \
	$(OBJDIR)/ReportLocalWaypoint.o \
	$(OBJDIR)/QueryGeomagneticProperty.o \
	$(OBJDIR)/QueryAccelerationLimit.o \
	$(OBJDIR)/ReportGlobalWaypoint.o \
	$(OBJDIR)/ReportLocalVector.o \
	$(OBJDIR)/SetGlobalVector.o \
	$(OBJDIR)/SetGlobalPathSegment.o \
	$(OBJDIR)/SetGlobalWaypoint.o \
	$(OBJDIR)/SetVelocityCommand.o \
	$(OBJDIR)/QueryLocalWaypoint.o \
	$(OBJDIR)/SetWrenchEffort.o \
	$(OBJDIR)/SetLocalPathSegment.o \
	$(OBJDIR)/ReportWrenchEffort.o \
	$(OBJDIR)/ReportLocalPathSegment.o \
	$(OBJDIR)/ReportGeomagneticProperty.o \
	$(OBJDIR)/QueryWrenchEffort.o \
	$(OBJDIR)/SetElement.o \
	$(OBJDIR)/QueryLocalPose.o \
	$(OBJDIR)/SetLocalVector.o \
	$(OBJDIR)/QueryGlobalVector.o \
	$(OBJDIR)/ExecuteList.o \
	$(OBJDIR)/ReportElementCount.o \
	$(OBJDIR)/QueryAccelerationState.o \
	$(OBJDIR)/QueryElementList.o \
	$(OBJDIR)/QueryGlobalWaypoint.o \
	$(OBJDIR)/DeleteElement.o \
	$(OBJDIR)/QueryLocalPathSegment.o \
	$(OBJDIR)/RejectElementRequest.o \
	$(OBJDIR)/LocalPositionScaledInteger.o \
	$(OBJDIR)/WeightingFactorRefScaledInteger.o \
	$(OBJDIR)/ExecuteListRecord.o \
	$(OBJDIR)/ResistiveEffortScaledInteger.o \
	$(OBJDIR)/VelocityCommandTypeEnumeration.o \
	$(OBJDIR)/AccelerationLimitRecord.o \
	$(OBJDIR)/AngularAccelerationRmsScaledInteger.o \
	$(OBJDIR)/DeleteElementList.o \
	$(OBJDIR)/AngularAccelerationScaledInteger.o \
	$(OBJDIR)/VelocityCommandRecord.o \
	$(OBJDIR)/LinearVelocityRmsScaledInteger.o \
	$(OBJDIR)/GlobalWaypointRecord.o \
	$(OBJDIR)/LocalVectorRecord.o \
	$(OBJDIR)/AccelerationCommandTypeEnumeration.o \
	$(OBJDIR)/MagneticVariationRefScaledInteger.o \
	$(OBJDIR)/WrenchEffortRecord.o \
	$(OBJDIR)/GlobalPathSegmentRecord.o \
	$(OBJDIR)/LocalPositionRmsScaledInteger.o \
	$(OBJDIR)/OrientationRmsScaledInteger.o \
	$(OBJDIR)/RejectElementResponseCodeEnumeration.o \
	$(OBJDIR)/ElementListRefArray.o \
	$(OBJDIR)/JausTimeStampBitField.o \
	$(OBJDIR)/PropulsiveEffortScaledInteger.o \
	$(OBJDIR)/LocalWaypointRecord.o \
	$(OBJDIR)/ElementRecord.o \
	$(OBJDIR)/LinearSpeedScaledInteger.o \
	$(OBJDIR)/LinearVelocityScaledInteger.o \
	$(OBJDIR)/LinearAccelerationScaledInteger.o \
	$(OBJDIR)/JausLongitudeScaledInteger.o \
	$(OBJDIR)/ResponseCodeEnumeration.o \
	$(OBJDIR)/LocalPoseRecord.o \
	$(OBJDIR)/AngularVelocityScaledInteger.o \
	$(OBJDIR)/GlobalPoseRecord.o \
	$(OBJDIR)/WaypointToleranceRefScaledInteger.o \
	$(OBJDIR)/JausLatitudeScaledInteger.o \
	$(OBJDIR)/PathToleranceRefScaledInteger.o \
	$(OBJDIR)/AngularVelocityRmsScaledInteger.o \
	$(OBJDIR)/GlobalVectorRecord.o \
	$(OBJDIR)/ElementIdList.o \
	$(OBJDIR)/JausAltitudeScaledInteger.o \
	$(OBJDIR)/OrientationScaledInteger.o \
	$(OBJDIR)/LocalPathSegmentRecord.o \
	$(OBJDIR)/LinearAccelerationRmsScaledInteger.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking openjaus-mobility
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning openjaus-mobility
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/GlobalPathSegmentDriver.o: ../src/openjaus/mobility/GlobalPathSegmentDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalWaypointDriver.o: ../src/openjaus/mobility/LocalWaypointDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPathSegmentDriver.o: ../src/openjaus/mobility/LocalPathSegmentDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveDriver.o: ../src/openjaus/mobility/PrimitiveDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VelocityStateDriver.o: ../src/openjaus/mobility/VelocityStateDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalWaypointListDriver.o: ../src/openjaus/mobility/LocalWaypointListDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalWaypointListDriver.o: ../src/openjaus/mobility/GlobalWaypointListDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AccelerationStateSensor.o: ../src/openjaus/mobility/AccelerationStateSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VelocityStateSensor.o: ../src/openjaus/mobility/VelocityStateSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPoseSensor.o: ../src/openjaus/mobility/LocalPoseSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalVectorDriver.o: ../src/openjaus/mobility/LocalVectorDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalWaypointDriver.o: ../src/openjaus/mobility/GlobalWaypointDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalVectorDriver.o: ../src/openjaus/mobility/GlobalVectorDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalPoseSensor.o: ../src/openjaus/mobility/GlobalPoseSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ListManaged.o: ../src/openjaus/mobility/ListManaged.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalVectorReadyLoop.o: ../src/openjaus/mobility/Transitions/GlobalVectorReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPoseControlledLoop.o: ../src/openjaus/mobility/Transitions/LocalPoseControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwldControlledLoop.o: ../src/openjaus/mobility/Transitions/LwldControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GposDefaultLoop.o: ../src/openjaus/mobility/Transitions/GposDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VelocityStateDefaultLoop.o: ../src/openjaus/mobility/Transitions/VelocityStateDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwldDefaultLoop.o: ../src/openjaus/mobility/Transitions/LwldDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalVectorDefaultLoop.o: ../src/openjaus/mobility/Transitions/GlobalVectorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GposControlledLoop.o: ../src/openjaus/mobility/Transitions/GposControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwdControlledLoop.o: ../src/openjaus/mobility/Transitions/GwdControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LpsdReadyLoop.o: ../src/openjaus/mobility/Transitions/LpsdReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwldControlledLoop.o: ../src/openjaus/mobility/Transitions/GwldControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VsdDefaultLoop.o: ../src/openjaus/mobility/Transitions/VsdDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwdReadyLoop.o: ../src/openjaus/mobility/Transitions/GwdReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwldDefaultLoop.o: ../src/openjaus/mobility/Transitions/GwldDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LpsdControlledLoop.o: ../src/openjaus/mobility/Transitions/LpsdControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPoseDefaultLoop.o: ../src/openjaus/mobility/Transitions/LocalPoseDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwdDefaultLoop.o: ../src/openjaus/mobility/Transitions/GwdDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LpsdDefaultLoop.o: ../src/openjaus/mobility/Transitions/LpsdDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveDriverReadyLoop.o: ../src/openjaus/mobility/Transitions/PrimitiveDriverReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AccelerationStateDefaultLoop.o: ../src/openjaus/mobility/Transitions/AccelerationStateDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VsdControlledLoop.o: ../src/openjaus/mobility/Transitions/VsdControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwdDefaultLoop.o: ../src/openjaus/mobility/Transitions/LwdDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwdControlledLoop.o: ../src/openjaus/mobility/Transitions/LwdControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ListManagerDefaultLoop.o: ../src/openjaus/mobility/Transitions/ListManagerDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GpsdReadyLoop.o: ../src/openjaus/mobility/Transitions/GpsdReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveDriverDefaultLoop.o: ../src/openjaus/mobility/Transitions/PrimitiveDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VsdReadyLoop.o: ../src/openjaus/mobility/Transitions/VsdReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalVectorReadyLoop.o: ../src/openjaus/mobility/Transitions/LocalVectorReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GpsdControlledLoop.o: ../src/openjaus/mobility/Transitions/GpsdControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GpsdDefaultLoop.o: ../src/openjaus/mobility/Transitions/GpsdDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwldReadyLoop.o: ../src/openjaus/mobility/Transitions/LwldReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LwdReadyLoop.o: ../src/openjaus/mobility/Transitions/LwdReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ListManagerControlledLoop.o: ../src/openjaus/mobility/Transitions/ListManagerControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GwldReadyLoop.o: ../src/openjaus/mobility/Transitions/GwldReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalVectorDefaultLoop.o: ../src/openjaus/mobility/Transitions/LocalVectorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryActiveElement.o: ../src/openjaus/mobility/Triggers/QueryActiveElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetLocalPose.o: ../src/openjaus/mobility/Triggers/SetLocalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetGeomagneticProperty.o: ../src/openjaus/mobility/Triggers/SetGeomagneticProperty.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportElementList.o: ../src/openjaus/mobility/Triggers/ReportElementList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportAccelerationState.o: ../src/openjaus/mobility/Triggers/ReportAccelerationState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVelocityCommand.o: ../src/openjaus/mobility/Triggers/QueryVelocityCommand.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetGlobalPose.o: ../src/openjaus/mobility/Triggers/SetGlobalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportGlobalPose.o: ../src/openjaus/mobility/Triggers/ReportGlobalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVelocityState.o: ../src/openjaus/mobility/Triggers/QueryVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetAccelerationLimit.o: ../src/openjaus/mobility/Triggers/SetAccelerationLimit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetLocalWaypoint.o: ../src/openjaus/mobility/Triggers/SetLocalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportLocalPose.o: ../src/openjaus/mobility/Triggers/ReportLocalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryLocalVector.o: ../src/openjaus/mobility/Triggers/QueryLocalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportActiveElement.o: ../src/openjaus/mobility/Triggers/ReportActiveElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmElementRequest.o: ../src/openjaus/mobility/Triggers/ConfirmElementRequest.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryElement.o: ../src/openjaus/mobility/Triggers/QueryElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportElement.o: ../src/openjaus/mobility/Triggers/ReportElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryGlobalPose.o: ../src/openjaus/mobility/Triggers/QueryGlobalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportVelocityState.o: ../src/openjaus/mobility/Triggers/ReportVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetTravelSpeed.o: ../src/openjaus/mobility/Triggers/SetTravelSpeed.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportGlobalPathSegment.o: ../src/openjaus/mobility/Triggers/ReportGlobalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryElementCount.o: ../src/openjaus/mobility/Triggers/QueryElementCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportAccelerationLimit.o: ../src/openjaus/mobility/Triggers/ReportAccelerationLimit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportTravelSpeed.o: ../src/openjaus/mobility/Triggers/ReportTravelSpeed.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportVelocityCommand.o: ../src/openjaus/mobility/Triggers/ReportVelocityCommand.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryTravelSpeed.o: ../src/openjaus/mobility/Triggers/QueryTravelSpeed.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportGlobalVector.o: ../src/openjaus/mobility/Triggers/ReportGlobalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryGlobalPathSegment.o: ../src/openjaus/mobility/Triggers/QueryGlobalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportLocalWaypoint.o: ../src/openjaus/mobility/Triggers/ReportLocalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryGeomagneticProperty.o: ../src/openjaus/mobility/Triggers/QueryGeomagneticProperty.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryAccelerationLimit.o: ../src/openjaus/mobility/Triggers/QueryAccelerationLimit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportGlobalWaypoint.o: ../src/openjaus/mobility/Triggers/ReportGlobalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportLocalVector.o: ../src/openjaus/mobility/Triggers/ReportLocalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetGlobalVector.o: ../src/openjaus/mobility/Triggers/SetGlobalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetGlobalPathSegment.o: ../src/openjaus/mobility/Triggers/SetGlobalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetGlobalWaypoint.o: ../src/openjaus/mobility/Triggers/SetGlobalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetVelocityCommand.o: ../src/openjaus/mobility/Triggers/SetVelocityCommand.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryLocalWaypoint.o: ../src/openjaus/mobility/Triggers/QueryLocalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetWrenchEffort.o: ../src/openjaus/mobility/Triggers/SetWrenchEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetLocalPathSegment.o: ../src/openjaus/mobility/Triggers/SetLocalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportWrenchEffort.o: ../src/openjaus/mobility/Triggers/ReportWrenchEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportLocalPathSegment.o: ../src/openjaus/mobility/Triggers/ReportLocalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportGeomagneticProperty.o: ../src/openjaus/mobility/Triggers/ReportGeomagneticProperty.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryWrenchEffort.o: ../src/openjaus/mobility/Triggers/QueryWrenchEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetElement.o: ../src/openjaus/mobility/Triggers/SetElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryLocalPose.o: ../src/openjaus/mobility/Triggers/QueryLocalPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetLocalVector.o: ../src/openjaus/mobility/Triggers/SetLocalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryGlobalVector.o: ../src/openjaus/mobility/Triggers/QueryGlobalVector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExecuteList.o: ../src/openjaus/mobility/Triggers/ExecuteList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportElementCount.o: ../src/openjaus/mobility/Triggers/ReportElementCount.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryAccelerationState.o: ../src/openjaus/mobility/Triggers/QueryAccelerationState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryElementList.o: ../src/openjaus/mobility/Triggers/QueryElementList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryGlobalWaypoint.o: ../src/openjaus/mobility/Triggers/QueryGlobalWaypoint.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DeleteElement.o: ../src/openjaus/mobility/Triggers/DeleteElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryLocalPathSegment.o: ../src/openjaus/mobility/Triggers/QueryLocalPathSegment.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RejectElementRequest.o: ../src/openjaus/mobility/Triggers/RejectElementRequest.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPositionScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LocalPositionScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WeightingFactorRefScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/WeightingFactorRefScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExecuteListRecord.o: ../src/openjaus/mobility/Triggers/Fields/ExecuteListRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ResistiveEffortScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/ResistiveEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VelocityCommandTypeEnumeration.o: ../src/openjaus/mobility/Triggers/Fields/VelocityCommandTypeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AccelerationLimitRecord.o: ../src/openjaus/mobility/Triggers/Fields/AccelerationLimitRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularAccelerationRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/AngularAccelerationRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DeleteElementList.o: ../src/openjaus/mobility/Triggers/Fields/DeleteElementList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularAccelerationScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/AngularAccelerationScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VelocityCommandRecord.o: ../src/openjaus/mobility/Triggers/Fields/VelocityCommandRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearVelocityRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LinearVelocityRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalWaypointRecord.o: ../src/openjaus/mobility/Triggers/Fields/GlobalWaypointRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalVectorRecord.o: ../src/openjaus/mobility/Triggers/Fields/LocalVectorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AccelerationCommandTypeEnumeration.o: ../src/openjaus/mobility/Triggers/Fields/AccelerationCommandTypeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MagneticVariationRefScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/MagneticVariationRefScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WrenchEffortRecord.o: ../src/openjaus/mobility/Triggers/Fields/WrenchEffortRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalPathSegmentRecord.o: ../src/openjaus/mobility/Triggers/Fields/GlobalPathSegmentRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPositionRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LocalPositionRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OrientationRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/OrientationRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RejectElementResponseCodeEnumeration.o: ../src/openjaus/mobility/Triggers/Fields/RejectElementResponseCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ElementListRefArray.o: ../src/openjaus/mobility/Triggers/Fields/ElementListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JausTimeStampBitField.o: ../src/openjaus/mobility/Triggers/Fields/JausTimeStampBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PropulsiveEffortScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/PropulsiveEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalWaypointRecord.o: ../src/openjaus/mobility/Triggers/Fields/LocalWaypointRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ElementRecord.o: ../src/openjaus/mobility/Triggers/Fields/ElementRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearSpeedScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LinearSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearVelocityScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LinearVelocityScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearAccelerationScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LinearAccelerationScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JausLongitudeScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/JausLongitudeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ResponseCodeEnumeration.o: ../src/openjaus/mobility/Triggers/Fields/ResponseCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPoseRecord.o: ../src/openjaus/mobility/Triggers/Fields/LocalPoseRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularVelocityScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/AngularVelocityScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalPoseRecord.o: ../src/openjaus/mobility/Triggers/Fields/GlobalPoseRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WaypointToleranceRefScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/WaypointToleranceRefScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JausLatitudeScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/JausLatitudeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PathToleranceRefScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/PathToleranceRefScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularVelocityRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/AngularVelocityRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GlobalVectorRecord.o: ../src/openjaus/mobility/Triggers/Fields/GlobalVectorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ElementIdList.o: ../src/openjaus/mobility/Triggers/Fields/ElementIdList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JausAltitudeScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/JausAltitudeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OrientationScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/OrientationScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LocalPathSegmentRecord.o: ../src/openjaus/mobility/Triggers/Fields/LocalPathSegmentRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearAccelerationRmsScaledInteger.o: ../src/openjaus/mobility/Triggers/Fields/LinearAccelerationRmsScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
