# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = Debug/openjaus-manipulator
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-manipulator.so
  DEFINES   += -DDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = Release/openjaus-manipulator
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-manipulator.so
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/ManipulatorActuatorForceTorqueDriver.o \
	$(OBJDIR)/PrimitiveManipulator.o \
	$(OBJDIR)/PanTiltJointVelocityDriver.o \
	$(OBJDIR)/ManipulatorEndEffectorPoseListDriver.o \
	$(OBJDIR)/ManipulatorJointPositionDriver.o \
	$(OBJDIR)/ManipulatorEndEffectorVelocityStateDriver.o \
	$(OBJDIR)/PanTiltJointPositionDriver.o \
	$(OBJDIR)/ManipulatorEndEffectorPoseSensor.o \
	$(OBJDIR)/PrimitivePanTilt.o \
	$(OBJDIR)/PanTiltJointPositionSensor.o \
	$(OBJDIR)/ManipulatorEndEffectorPoseDriver.o \
	$(OBJDIR)/ManipulatorJointPositionSensor.o \
	$(OBJDIR)/ManipulatorEndEffectorVelocityStateSensor.o \
	$(OBJDIR)/ManipulatorJointPositionListDriver.o \
	$(OBJDIR)/PanTiltJointVelocitySensor.o \
	$(OBJDIR)/ManipulatorJointForceTorqueSensor.o \
	$(OBJDIR)/ManipulatorJointVelocityDriver.o \
	$(OBJDIR)/PrimitiveEndEffector.o \
	$(OBJDIR)/ManipulatorJointVelocitySensor.o \
	$(OBJDIR)/EndEffectorVelocityStateDriverDefaultLoop.o \
	$(OBJDIR)/PanTiltJointVelocityDriverControlledLoop.o \
	$(OBJDIR)/JointPositionSensorDefaultLoop.o \
	$(OBJDIR)/JointPositionDriverControlledLoop.o \
	$(OBJDIR)/EndEffectorPoseSensorDefaultLoop.o \
	$(OBJDIR)/PrimitiveEndEffectorControlledLoop.o \
	$(OBJDIR)/JointForceTorqueSensorDefaultLoop.o \
	$(OBJDIR)/JointVelocityDriverDefaultLoop.o \
	$(OBJDIR)/PanTiltJointVelocitySensorDefaultLoop.o \
	$(OBJDIR)/JointPositionListDriverDefaultLoop.o \
	$(OBJDIR)/PanTiltJointPositionSensorDefaultLoop.o \
	$(OBJDIR)/PrimitiveManipulatorControlledLoop.o \
	$(OBJDIR)/PrimitivePanTiltDefaultLoop.o \
	$(OBJDIR)/EndEffectorPoseSensorControlledLoop.o \
	$(OBJDIR)/PrimitiveEndEffectorDefaultLoop.o \
	$(OBJDIR)/EndEffectorVelocityStateSensorDefaultLoop.o \
	$(OBJDIR)/EndEffectorPoseDriverDefaultLoop.o \
	$(OBJDIR)/EndEffectorPoseListDriverDefaultLoop.o \
	$(OBJDIR)/EndEffectorVelocityStateDriverControlledLoop.o \
	$(OBJDIR)/JointPositionListDriverControlledLoop.o \
	$(OBJDIR)/EndEffectorPoseDriverControlledLoop.o \
	$(OBJDIR)/ActuatorForceTorqueDefaultLoop.o \
	$(OBJDIR)/PanTiltJointVelocityDriverDefaultLoop.o \
	$(OBJDIR)/EndEffectorPoseListDriverControlledLoop.o \
	$(OBJDIR)/JointPositionDriverDefaultLoop.o \
	$(OBJDIR)/EndEffectorVelocityStateSensorControlledLoop.o \
	$(OBJDIR)/PrimitivePanTiltControlledLoop.o \
	$(OBJDIR)/PrimitiveManipulatorDefaultLoop.o \
	$(OBJDIR)/JointVelocityDriverControlledLoop.o \
	$(OBJDIR)/ActuatorForceTorqueDriverControlledLoop.o \
	$(OBJDIR)/JointVelocitySensorDefaultLoop.o \
	$(OBJDIR)/PanTiltPositionDriverControlledLoop.o \
	$(OBJDIR)/PanTiltPositionDriverDefaultLoop.o \
	$(OBJDIR)/QueryPanTiltSpecifications.o \
	$(OBJDIR)/QueryActiveElement.o \
	$(OBJDIR)/QueryJointMotionProfile.o \
	$(OBJDIR)/QueryPanTiltJointPosition.o \
	$(OBJDIR)/SetEndEffectorPose.o \
	$(OBJDIR)/QueryEndEffectorEffort.o \
	$(OBJDIR)/QueryJointVelocity.o \
	$(OBJDIR)/SetPanTiltJointVelocity.o \
	$(OBJDIR)/QueryCommandedPanTiltJointVelocity.o \
	$(OBJDIR)/ReportJointMotionProfile.o \
	$(OBJDIR)/QueryCommandedPanTiltJointPosition.o \
	$(OBJDIR)/ReportPanTiltSpecifications.o \
	$(OBJDIR)/ReportActiveElement.o \
	$(OBJDIR)/SetJointPosition.o \
	$(OBJDIR)/ReportCommandedPanTiltJointPosition.o \
	$(OBJDIR)/QueryCommandedActuatorForceTorque.o \
	$(OBJDIR)/QueryPanTiltMotionProfile.o \
	$(OBJDIR)/QueryCommandedEndEffectorPose.o \
	$(OBJDIR)/SetEndEffectorEffort.o \
	$(OBJDIR)/QueryEndEffectorPose.o \
	$(OBJDIR)/ReportCommandedJointVelocity.o \
	$(OBJDIR)/QueryCommandedEndEffectorVelocityState.o \
	$(OBJDIR)/ReportPanTiltMotionProfile.o \
	$(OBJDIR)/QueryEndEffectorVelocityState.o \
	$(OBJDIR)/ReportPanTiltJointVelocity.o \
	$(OBJDIR)/ReportToolOffset.o \
	$(OBJDIR)/ReportEndEffectorEffort.o \
	$(OBJDIR)/SetPanTiltJointEffort.o \
	$(OBJDIR)/ReportCommandedEndEffectorPose.o \
	$(OBJDIR)/SetJointVelocity.o \
	$(OBJDIR)/ReportJointForceTorque.o \
	$(OBJDIR)/ReportPanTiltJointPosition.o \
	$(OBJDIR)/QueryJointForceTorque.o \
	$(OBJDIR)/ReportJointVelocity.o \
	$(OBJDIR)/ReportEndEffectorSpecification.o \
	$(OBJDIR)/ReportEndEffectorVelocityState.o \
	$(OBJDIR)/SetPanTiltJointPosition.o \
	$(OBJDIR)/ReportJointEffort.o \
	$(OBJDIR)/ReportPanTiltJointEffort.o \
	$(OBJDIR)/ReportCommandedEndEffectorVelocityState.o \
	$(OBJDIR)/SetJointEffort.o \
	$(OBJDIR)/QueryEndEffectorSpecification.o \
	$(OBJDIR)/QueryPanTiltJointVelocity.o \
	$(OBJDIR)/QueryToolOffset.o \
	$(OBJDIR)/SetJointMotionProfile.o \
	$(OBJDIR)/QueryManipulatorSpecifications.o \
	$(OBJDIR)/ReportCommandedJointPosition.o \
	$(OBJDIR)/ReportEndEffectorPose.o \
	$(OBJDIR)/QueryJointEffort.o \
	$(OBJDIR)/ReportJointPosition.o \
	$(OBJDIR)/ReportCommandedActuatorForceTorque.o \
	$(OBJDIR)/ExecuteList.o \
	$(OBJDIR)/SetPanTiltMotionProfile.o \
	$(OBJDIR)/ReportManipulatorSpecifications.o \
	$(OBJDIR)/QueryPanTiltJointEffort.o \
	$(OBJDIR)/ReportCommandedPanTiltJointVelocity.o \
	$(OBJDIR)/QueryCommandedJointVelocity.o \
	$(OBJDIR)/QueryCommandedJointPosition.o \
	$(OBJDIR)/SetToolOffset.o \
	$(OBJDIR)/QueryJointPosition.o \
	$(OBJDIR)/SetActuatorForceTorque.o \
	$(OBJDIR)/SetEndEffectorVelocityState.o \
	$(OBJDIR)/ManipulatorCoordinateSysZScaledInteger.o \
	$(OBJDIR)/DComponentOfUnitQuaternionQScaledInteger.o \
	$(OBJDIR)/Joint1MaxValueScaledInteger.o \
	$(OBJDIR)/Joint1VelocityScaledInteger.o \
	$(OBJDIR)/Joint2EffortScaledInteger.o \
	$(OBJDIR)/PanTiltCoordinateSysZScaledInteger.o \
	$(OBJDIR)/AngularVelocityComponentYScaledInteger.o \
	$(OBJDIR)/AngularVelocityComponentZScaledInteger.o \
	$(OBJDIR)/JointAngleScaledInteger.o \
	$(OBJDIR)/MaxSpeedScaledInteger.o \
	$(OBJDIR)/JointEffortRecord.o \
	$(OBJDIR)/BComponentOfUnitQuaternionQScaledInteger.o \
	$(OBJDIR)/Joint1OffsetScaledInteger.o \
	$(OBJDIR)/PrismaticJointMotionProfileRecord.o \
	$(OBJDIR)/JointSpecificationList.o \
	$(OBJDIR)/Joint1PositionScaledInteger.o \
	$(OBJDIR)/Option1ScaledInteger.o \
	$(OBJDIR)/EndEffectorEffortScaledInteger.o \
	$(OBJDIR)/Joint1MinValueScaledInteger.o \
	$(OBJDIR)/ToolPointCoordinateYScaledInteger.o \
	$(OBJDIR)/PrismaticJointSpecificationRecord.o \
	$(OBJDIR)/Joint2PositionScaledInteger.o \
	$(OBJDIR)/RevoluteJointSpecificationRecord.o \
	$(OBJDIR)/JointMaxAccelerationRateScaledInteger.o \
	$(OBJDIR)/TwistAngleScaledInteger.o \
	$(OBJDIR)/Joint2MaxAccelerationRateScaledInteger.o \
	$(OBJDIR)/Joint1MaxAccelerationRateScaledInteger.o \
	$(OBJDIR)/JointEffortList.o \
	$(OBJDIR)/Joint2MaxDecelerationRateScaledInteger.o \
	$(OBJDIR)/ToolPointCoordinateXScaledInteger.o \
	$(OBJDIR)/ManipulatorCoordinateSysYScaledInteger.o \
	$(OBJDIR)/PrismaticJoint1AngleRecord.o \
	$(OBJDIR)/LinearVelocityComponentXScaledInteger.o \
	$(OBJDIR)/ParentIDBitField.o \
	$(OBJDIR)/Joint2MinValueScaledInteger.o \
	$(OBJDIR)/ToolPointCoordinateZScaledInteger.o \
	$(OBJDIR)/JointMotionProfileList.o \
	$(OBJDIR)/ManipulatorCoordinateSystemRecord.o \
	$(OBJDIR)/Joint1EffortScaledInteger.o \
	$(OBJDIR)/Joint1MaxSpeedScaledInteger.o \
	$(OBJDIR)/JointEffortScaledInteger.o \
	$(OBJDIR)/LinearVelocityComponentZScaledInteger.o \
	$(OBJDIR)/JointPositionRecord.o \
	$(OBJDIR)/AComponentOfUnitQuaternionQScaledInteger.o \
	$(OBJDIR)/Joint1AngleScaledInteger.o \
	$(OBJDIR)/Joint1MaxDecelerationRateScaledInteger.o \
	$(OBJDIR)/LinkLengthScaledInteger.o \
	$(OBJDIR)/ActuatorForceTorqueRecord.o \
	$(OBJDIR)/AngularVelocityComponentXScaledInteger.o \
	$(OBJDIR)/JointMaxSpeedScaledInteger.o \
	$(OBJDIR)/Joint2MaxValueScaledInteger.o \
	$(OBJDIR)/MaxTorqueScaledInteger.o \
	$(OBJDIR)/Joint1MaxTorqueScaledInteger.o \
	$(OBJDIR)/Option0ScaledInteger.o \
	$(OBJDIR)/JointOffsetScaledInteger.o \
	$(OBJDIR)/PanTiltCoordinateSysYScaledInteger.o \
	$(OBJDIR)/FirstJointParametersVariant.o \
	$(OBJDIR)/JointMaxDecelerationRateScaledInteger.o \
	$(OBJDIR)/JointVelocityList.o \
	$(OBJDIR)/RevoluteJoint1OffsetRecord.o \
	$(OBJDIR)/JointForceTorqueVariant.o \
	$(OBJDIR)/JointPositionVariant.o \
	$(OBJDIR)/Joint2MaxSpeedScaledInteger.o \
	$(OBJDIR)/Joint2VelocityScaledInteger.o \
	$(OBJDIR)/PanTiltCoordinateSysXScaledInteger.o \
	$(OBJDIR)/MinValueScaledInteger.o \
	$(OBJDIR)/JointVelocityVariant.o \
	$(OBJDIR)/MaxForceScaledInteger.o \
	$(OBJDIR)/MaxValueScaledInteger.o \
	$(OBJDIR)/JointPositionList.o \
	$(OBJDIR)/JointVelocityRecord.o \
	$(OBJDIR)/CComponentOfUnitQuaternionQScaledInteger.o \
	$(OBJDIR)/JointSpecificationsVariant.o \
	$(OBJDIR)/LinearVelocityComponentYScaledInteger.o \
	$(OBJDIR)/ManipulatorCoordinateSysXScaledInteger.o \
	$(OBJDIR)/ActuatorForceTorqueList.o \
	$(OBJDIR)/Joint1MaxForceScaledInteger.o \
	$(OBJDIR)/RevoluteJointMotionProfileRecord.o \
	$(OBJDIR)/JointTypeVariant.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking openjaus-manipulator
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning openjaus-manipulator
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/ManipulatorActuatorForceTorqueDriver.o: ../src/openjaus/manipulator/ManipulatorActuatorForceTorqueDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveManipulator.o: ../src/openjaus/manipulator/PrimitiveManipulator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointVelocityDriver.o: ../src/openjaus/manipulator/PanTiltJointVelocityDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorEndEffectorPoseListDriver.o: ../src/openjaus/manipulator/ManipulatorEndEffectorPoseListDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointPositionDriver.o: ../src/openjaus/manipulator/ManipulatorJointPositionDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorEndEffectorVelocityStateDriver.o: ../src/openjaus/manipulator/ManipulatorEndEffectorVelocityStateDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointPositionDriver.o: ../src/openjaus/manipulator/PanTiltJointPositionDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorEndEffectorPoseSensor.o: ../src/openjaus/manipulator/ManipulatorEndEffectorPoseSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitivePanTilt.o: ../src/openjaus/manipulator/PrimitivePanTilt.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointPositionSensor.o: ../src/openjaus/manipulator/PanTiltJointPositionSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorEndEffectorPoseDriver.o: ../src/openjaus/manipulator/ManipulatorEndEffectorPoseDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointPositionSensor.o: ../src/openjaus/manipulator/ManipulatorJointPositionSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorEndEffectorVelocityStateSensor.o: ../src/openjaus/manipulator/ManipulatorEndEffectorVelocityStateSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointPositionListDriver.o: ../src/openjaus/manipulator/ManipulatorJointPositionListDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointVelocitySensor.o: ../src/openjaus/manipulator/PanTiltJointVelocitySensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointForceTorqueSensor.o: ../src/openjaus/manipulator/ManipulatorJointForceTorqueSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointVelocityDriver.o: ../src/openjaus/manipulator/ManipulatorJointVelocityDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveEndEffector.o: ../src/openjaus/manipulator/PrimitiveEndEffector.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorJointVelocitySensor.o: ../src/openjaus/manipulator/ManipulatorJointVelocitySensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorVelocityStateDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorVelocityStateDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointVelocityDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltJointVelocityDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionSensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointPositionSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/JointPositionDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseSensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveEndEffectorControlledLoop.o: ../src/openjaus/manipulator/Transitions/PrimitiveEndEffectorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointForceTorqueSensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointForceTorqueSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocityDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointVelocityDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointVelocitySensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltJointVelocitySensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionListDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointPositionListDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointPositionSensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltJointPositionSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveManipulatorControlledLoop.o: ../src/openjaus/manipulator/Transitions/PrimitiveManipulatorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitivePanTiltDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PrimitivePanTiltDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseSensorControlledLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseSensorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveEndEffectorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PrimitiveEndEffectorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorVelocityStateSensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorVelocityStateSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseListDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseListDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorVelocityStateDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorVelocityStateDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionListDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/JointPositionListDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ActuatorForceTorqueDefaultLoop.o: ../src/openjaus/manipulator/Transitions/ActuatorForceTorqueDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltJointVelocityDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltJointVelocityDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorPoseListDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorPoseListDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointPositionDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorVelocityStateSensorControlledLoop.o: ../src/openjaus/manipulator/Transitions/EndEffectorVelocityStateSensorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitivePanTiltControlledLoop.o: ../src/openjaus/manipulator/Transitions/PrimitivePanTiltControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrimitiveManipulatorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PrimitiveManipulatorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocityDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/JointVelocityDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ActuatorForceTorqueDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/ActuatorForceTorqueDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocitySensorDefaultLoop.o: ../src/openjaus/manipulator/Transitions/JointVelocitySensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltPositionDriverControlledLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltPositionDriverControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltPositionDriverDefaultLoop.o: ../src/openjaus/manipulator/Transitions/PanTiltPositionDriverDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPanTiltSpecifications.o: ../src/openjaus/manipulator/Triggers/QueryPanTiltSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryActiveElement.o: ../src/openjaus/manipulator/Triggers/QueryActiveElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryJointMotionProfile.o: ../src/openjaus/manipulator/Triggers/QueryJointMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPanTiltJointPosition.o: ../src/openjaus/manipulator/Triggers/QueryPanTiltJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetEndEffectorPose.o: ../src/openjaus/manipulator/Triggers/SetEndEffectorPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryEndEffectorEffort.o: ../src/openjaus/manipulator/Triggers/QueryEndEffectorEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryJointVelocity.o: ../src/openjaus/manipulator/Triggers/QueryJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetPanTiltJointVelocity.o: ../src/openjaus/manipulator/Triggers/SetPanTiltJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedPanTiltJointVelocity.o: ../src/openjaus/manipulator/Triggers/QueryCommandedPanTiltJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportJointMotionProfile.o: ../src/openjaus/manipulator/Triggers/ReportJointMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedPanTiltJointPosition.o: ../src/openjaus/manipulator/Triggers/QueryCommandedPanTiltJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPanTiltSpecifications.o: ../src/openjaus/manipulator/Triggers/ReportPanTiltSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportActiveElement.o: ../src/openjaus/manipulator/Triggers/ReportActiveElement.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetJointPosition.o: ../src/openjaus/manipulator/Triggers/SetJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedPanTiltJointPosition.o: ../src/openjaus/manipulator/Triggers/ReportCommandedPanTiltJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedActuatorForceTorque.o: ../src/openjaus/manipulator/Triggers/QueryCommandedActuatorForceTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPanTiltMotionProfile.o: ../src/openjaus/manipulator/Triggers/QueryPanTiltMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedEndEffectorPose.o: ../src/openjaus/manipulator/Triggers/QueryCommandedEndEffectorPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetEndEffectorEffort.o: ../src/openjaus/manipulator/Triggers/SetEndEffectorEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryEndEffectorPose.o: ../src/openjaus/manipulator/Triggers/QueryEndEffectorPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedJointVelocity.o: ../src/openjaus/manipulator/Triggers/ReportCommandedJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedEndEffectorVelocityState.o: ../src/openjaus/manipulator/Triggers/QueryCommandedEndEffectorVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPanTiltMotionProfile.o: ../src/openjaus/manipulator/Triggers/ReportPanTiltMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryEndEffectorVelocityState.o: ../src/openjaus/manipulator/Triggers/QueryEndEffectorVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPanTiltJointVelocity.o: ../src/openjaus/manipulator/Triggers/ReportPanTiltJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportToolOffset.o: ../src/openjaus/manipulator/Triggers/ReportToolOffset.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportEndEffectorEffort.o: ../src/openjaus/manipulator/Triggers/ReportEndEffectorEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetPanTiltJointEffort.o: ../src/openjaus/manipulator/Triggers/SetPanTiltJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedEndEffectorPose.o: ../src/openjaus/manipulator/Triggers/ReportCommandedEndEffectorPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetJointVelocity.o: ../src/openjaus/manipulator/Triggers/SetJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportJointForceTorque.o: ../src/openjaus/manipulator/Triggers/ReportJointForceTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPanTiltJointPosition.o: ../src/openjaus/manipulator/Triggers/ReportPanTiltJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryJointForceTorque.o: ../src/openjaus/manipulator/Triggers/QueryJointForceTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportJointVelocity.o: ../src/openjaus/manipulator/Triggers/ReportJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportEndEffectorSpecification.o: ../src/openjaus/manipulator/Triggers/ReportEndEffectorSpecification.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportEndEffectorVelocityState.o: ../src/openjaus/manipulator/Triggers/ReportEndEffectorVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetPanTiltJointPosition.o: ../src/openjaus/manipulator/Triggers/SetPanTiltJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportJointEffort.o: ../src/openjaus/manipulator/Triggers/ReportJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPanTiltJointEffort.o: ../src/openjaus/manipulator/Triggers/ReportPanTiltJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedEndEffectorVelocityState.o: ../src/openjaus/manipulator/Triggers/ReportCommandedEndEffectorVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetJointEffort.o: ../src/openjaus/manipulator/Triggers/SetJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryEndEffectorSpecification.o: ../src/openjaus/manipulator/Triggers/QueryEndEffectorSpecification.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPanTiltJointVelocity.o: ../src/openjaus/manipulator/Triggers/QueryPanTiltJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryToolOffset.o: ../src/openjaus/manipulator/Triggers/QueryToolOffset.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetJointMotionProfile.o: ../src/openjaus/manipulator/Triggers/SetJointMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryManipulatorSpecifications.o: ../src/openjaus/manipulator/Triggers/QueryManipulatorSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedJointPosition.o: ../src/openjaus/manipulator/Triggers/ReportCommandedJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportEndEffectorPose.o: ../src/openjaus/manipulator/Triggers/ReportEndEffectorPose.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryJointEffort.o: ../src/openjaus/manipulator/Triggers/QueryJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportJointPosition.o: ../src/openjaus/manipulator/Triggers/ReportJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedActuatorForceTorque.o: ../src/openjaus/manipulator/Triggers/ReportCommandedActuatorForceTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExecuteList.o: ../src/openjaus/manipulator/Triggers/ExecuteList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetPanTiltMotionProfile.o: ../src/openjaus/manipulator/Triggers/SetPanTiltMotionProfile.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportManipulatorSpecifications.o: ../src/openjaus/manipulator/Triggers/ReportManipulatorSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPanTiltJointEffort.o: ../src/openjaus/manipulator/Triggers/QueryPanTiltJointEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCommandedPanTiltJointVelocity.o: ../src/openjaus/manipulator/Triggers/ReportCommandedPanTiltJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedJointVelocity.o: ../src/openjaus/manipulator/Triggers/QueryCommandedJointVelocity.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryCommandedJointPosition.o: ../src/openjaus/manipulator/Triggers/QueryCommandedJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetToolOffset.o: ../src/openjaus/manipulator/Triggers/SetToolOffset.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryJointPosition.o: ../src/openjaus/manipulator/Triggers/QueryJointPosition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetActuatorForceTorque.o: ../src/openjaus/manipulator/Triggers/SetActuatorForceTorque.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetEndEffectorVelocityState.o: ../src/openjaus/manipulator/Triggers/SetEndEffectorVelocityState.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorCoordinateSysZScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ManipulatorCoordinateSysZScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DComponentOfUnitQuaternionQScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/DComponentOfUnitQuaternionQScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1VelocityScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1VelocityScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2EffortScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2EffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltCoordinateSysZScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/PanTiltCoordinateSysZScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularVelocityComponentYScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/AngularVelocityComponentYScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularVelocityComponentZScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/AngularVelocityComponentZScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointAngleScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaxSpeedScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/MaxSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointEffortRecord.o: ../src/openjaus/manipulator/Triggers/Fields/JointEffortRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BComponentOfUnitQuaternionQScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/BComponentOfUnitQuaternionQScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1OffsetScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1OffsetScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrismaticJointMotionProfileRecord.o: ../src/openjaus/manipulator/Triggers/Fields/PrismaticJointMotionProfileRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointSpecificationList.o: ../src/openjaus/manipulator/Triggers/Fields/JointSpecificationList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1PositionScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1PositionScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Option1ScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Option1ScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EndEffectorEffortScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/EndEffectorEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MinValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MinValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ToolPointCoordinateYScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ToolPointCoordinateYScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrismaticJointSpecificationRecord.o: ../src/openjaus/manipulator/Triggers/Fields/PrismaticJointSpecificationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2PositionScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2PositionScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RevoluteJointSpecificationRecord.o: ../src/openjaus/manipulator/Triggers/Fields/RevoluteJointSpecificationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointMaxAccelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointMaxAccelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TwistAngleScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/TwistAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2MaxAccelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2MaxAccelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxAccelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxAccelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointEffortList.o: ../src/openjaus/manipulator/Triggers/Fields/JointEffortList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2MaxDecelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2MaxDecelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ToolPointCoordinateXScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ToolPointCoordinateXScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorCoordinateSysYScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ManipulatorCoordinateSysYScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PrismaticJoint1AngleRecord.o: ../src/openjaus/manipulator/Triggers/Fields/PrismaticJoint1AngleRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearVelocityComponentXScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/LinearVelocityComponentXScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ParentIDBitField.o: ../src/openjaus/manipulator/Triggers/Fields/ParentIDBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2MinValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2MinValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ToolPointCoordinateZScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ToolPointCoordinateZScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointMotionProfileList.o: ../src/openjaus/manipulator/Triggers/Fields/JointMotionProfileList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorCoordinateSystemRecord.o: ../src/openjaus/manipulator/Triggers/Fields/ManipulatorCoordinateSystemRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1EffortScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1EffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxSpeedScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointEffortScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearVelocityComponentZScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/LinearVelocityComponentZScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionRecord.o: ../src/openjaus/manipulator/Triggers/Fields/JointPositionRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AComponentOfUnitQuaternionQScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/AComponentOfUnitQuaternionQScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1AngleScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1AngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxDecelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxDecelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinkLengthScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/LinkLengthScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ActuatorForceTorqueRecord.o: ../src/openjaus/manipulator/Triggers/Fields/ActuatorForceTorqueRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AngularVelocityComponentXScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/AngularVelocityComponentXScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointMaxSpeedScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointMaxSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2MaxValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2MaxValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaxTorqueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/MaxTorqueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxTorqueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxTorqueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Option0ScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Option0ScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointOffsetScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointOffsetScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltCoordinateSysYScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/PanTiltCoordinateSysYScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FirstJointParametersVariant.o: ../src/openjaus/manipulator/Triggers/Fields/FirstJointParametersVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointMaxDecelerationRateScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/JointMaxDecelerationRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocityList.o: ../src/openjaus/manipulator/Triggers/Fields/JointVelocityList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RevoluteJoint1OffsetRecord.o: ../src/openjaus/manipulator/Triggers/Fields/RevoluteJoint1OffsetRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointForceTorqueVariant.o: ../src/openjaus/manipulator/Triggers/Fields/JointForceTorqueVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionVariant.o: ../src/openjaus/manipulator/Triggers/Fields/JointPositionVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2MaxSpeedScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2MaxSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint2VelocityScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint2VelocityScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PanTiltCoordinateSysXScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/PanTiltCoordinateSysXScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/MinValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocityVariant.o: ../src/openjaus/manipulator/Triggers/Fields/JointVelocityVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaxForceScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/MaxForceScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaxValueScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/MaxValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointPositionList.o: ../src/openjaus/manipulator/Triggers/Fields/JointPositionList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointVelocityRecord.o: ../src/openjaus/manipulator/Triggers/Fields/JointVelocityRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CComponentOfUnitQuaternionQScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/CComponentOfUnitQuaternionQScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointSpecificationsVariant.o: ../src/openjaus/manipulator/Triggers/Fields/JointSpecificationsVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LinearVelocityComponentYScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/LinearVelocityComponentYScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorCoordinateSysXScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/ManipulatorCoordinateSysXScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ActuatorForceTorqueList.o: ../src/openjaus/manipulator/Triggers/Fields/ActuatorForceTorqueList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Joint1MaxForceScaledInteger.o: ../src/openjaus/manipulator/Triggers/Fields/Joint1MaxForceScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RevoluteJointMotionProfileRecord.o: ../src/openjaus/manipulator/Triggers/Fields/RevoluteJointMotionProfileRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JointTypeVariant.o: ../src/openjaus/manipulator/Triggers/Fields/JointTypeVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
