# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = Debug/openjaus-ugv
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-ugv.so
  DEFINES   += -DDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = Release/openjaus-ugv
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-ugv.so
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/SkidSteerDriver.o \
	$(OBJDIR)/SkidSteerReadyLoop.o \
	$(OBJDIR)/SkidSteerDefaultLoop.o \
	$(OBJDIR)/QueryPlatformSpecifications.o \
	$(OBJDIR)/QuerySkidSteerEffort.o \
	$(OBJDIR)/ReportSkidSteerEffort.o \
	$(OBJDIR)/SetSkidSteerEffort.o \
	$(OBJDIR)/ReportPlatformSpecifications.o \
	$(OBJDIR)/RightTrackPropulsiveEffortScaledInteger.o \
	$(OBJDIR)/LeftTrackPropulsiveEffortScaledInteger.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking openjaus-ugv
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning openjaus-ugv
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/SkidSteerDriver.o: ../src/openjaus/ugv/SkidSteerDriver.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkidSteerReadyLoop.o: ../src/openjaus/ugv/Transitions/SkidSteerReadyLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SkidSteerDefaultLoop.o: ../src/openjaus/ugv/Transitions/SkidSteerDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryPlatformSpecifications.o: ../src/openjaus/ugv/Triggers/QueryPlatformSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QuerySkidSteerEffort.o: ../src/openjaus/ugv/Triggers/QuerySkidSteerEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportSkidSteerEffort.o: ../src/openjaus/ugv/Triggers/ReportSkidSteerEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetSkidSteerEffort.o: ../src/openjaus/ugv/Triggers/SetSkidSteerEffort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportPlatformSpecifications.o: ../src/openjaus/ugv/Triggers/ReportPlatformSpecifications.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RightTrackPropulsiveEffortScaledInteger.o: ../src/openjaus/ugv/Triggers/Fields/RightTrackPropulsiveEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LeftTrackPropulsiveEffortScaledInteger.o: ../src/openjaus/ugv/Triggers/Fields/LeftTrackPropulsiveEffortScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
