# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = Debug/openjaus-environment
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-environment.so
  DEFINES   += -DDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = Release/openjaus-environment
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus-environment.so
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -L../lib
  LIBS      += -ljson -lopenjaus -lopenjaus-core -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so ../lib/libopenjaus.so ../lib/libopenjaus-core.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/StillImageSensor.o \
	$(OBJDIR)/RangeSensor.o \
	$(OBJDIR)/AnalogVideoSensor.o \
	$(OBJDIR)/DigitalVideoSensor.o \
	$(OBJDIR)/VisualSensorDefaultLoop.o \
	$(OBJDIR)/AnalogVideoControlledLoop.o \
	$(OBJDIR)/VisualSensorControlledLoop.o \
	$(OBJDIR)/RangeSensorControlledLoop.o \
	$(OBJDIR)/StillImageControlledLoop.o \
	$(OBJDIR)/StillImageDefaultLoop.o \
	$(OBJDIR)/RangeSensorDefaultLoop.o \
	$(OBJDIR)/AnalogVideoDefaultLoop.o \
	$(OBJDIR)/DigitalVideoControlledLoop.o \
	$(OBJDIR)/DigitalVideoDefaultLoop.o \
	$(OBJDIR)/ReportAnalogVideoSensorCapabilities.o \
	$(OBJDIR)/ReportVisualSensorCapabilities.o \
	$(OBJDIR)/QueryStillImageSensorCapabilities.o \
	$(OBJDIR)/ReportVisualSensorGeometricProperties.o \
	$(OBJDIR)/QueryVisualSensorConfiguration.o \
	$(OBJDIR)/ConfirmStillImageSensorConfiguration.o \
	$(OBJDIR)/ReportDigitalVideoSensorCapabilities.o \
	$(OBJDIR)/ConfirmAnalogVideoSensorConfiguration.o \
	$(OBJDIR)/ControlDigitalVideoSensorStream.o \
	$(OBJDIR)/QueryVisualSensorGeometricProperties.o \
	$(OBJDIR)/ReportStillImageSensorConfiguration.o \
	$(OBJDIR)/QueryRangeSensorData.o \
	$(OBJDIR)/SetStillImageSensorConfiguration.o \
	$(OBJDIR)/ReportRangeSensorGeometricProperties.o \
	$(OBJDIR)/QueryDigitalVideoSensorCapabilities.o \
	$(OBJDIR)/ConfirmDigitalVideoSensorConfiguration.o \
	$(OBJDIR)/ReportStillImageSensorCapabilities.o \
	$(OBJDIR)/QueryDigitalVideoSensorConfiguration.o \
	$(OBJDIR)/ReportRangeSensorCompressedData.o \
	$(OBJDIR)/ReportVisualSensorConfiguration.o \
	$(OBJDIR)/ConfirmVisualSensorConfiguration.o \
	$(OBJDIR)/SetAnalogVideoSensorConfiguration.o \
	$(OBJDIR)/SetRangeSensorConfiguration.o \
	$(OBJDIR)/ReportDigitalVideoSensorConfiguration.o \
	$(OBJDIR)/ReportRangeSensorCapabilities.o \
	$(OBJDIR)/QueryStillImageData.o \
	$(OBJDIR)/SetVisualSensorConfiguration.o \
	$(OBJDIR)/QueryRangeSensorCompressedData.o \
	$(OBJDIR)/ReportRangeSensorConfiguration.o \
	$(OBJDIR)/QuerySensorGeometricProperties.o \
	$(OBJDIR)/ReportAnalogVideoSensorConfiguration.o \
	$(OBJDIR)/QueryVisualSensorCapabilities.o \
	$(OBJDIR)/SetDigitalVideoSensorConfiguration.o \
	$(OBJDIR)/QueryAnalogVideoSensorConfiguration.o \
	$(OBJDIR)/ReportStillImageData.o \
	$(OBJDIR)/QueryStillImageSensorConfiguration.o \
	$(OBJDIR)/QueryRangeSensorConfiguration.o \
	$(OBJDIR)/QueryRangeSensorCapabilities.o \
	$(OBJDIR)/ReportRangeSensorData.o \
	$(OBJDIR)/QueryAnalogVideoSensorCapabilities.o \
	$(OBJDIR)/ConfirmRangeSensorConfiguration.o \
	$(OBJDIR)/RangeSensorDataErrorRecRefRecord.o \
	$(OBJDIR)/InclinationScaledInteger.o \
	$(OBJDIR)/RangeSensorDataPointRecord.o \
	$(OBJDIR)/BearingErrorRMSScaledInteger.o \
	$(OBJDIR)/MaximumUpdateRateScaledInteger.o \
	$(OBJDIR)/QueryDigitalVideoSensorCapabilitiesList.o \
	$(OBJDIR)/AnalogVideoSensorCapabilitiesRecord.o \
	$(OBJDIR)/SupportedImageFormatsBitField.o \
	$(OBJDIR)/StaticGeometricPropertiesRecord.o \
	$(OBJDIR)/DigitalFormatEnumeration.o \
	$(OBJDIR)/DigitalVideoSensorConfigurationListRefArray.o \
	$(OBJDIR)/QueryDigitalVideoSensorCapabilitiesRecord.o \
	$(OBJDIR)/StillImageErrorCodeEnumeration.o \
	$(OBJDIR)/RangeSensorDataRecord.o \
	$(OBJDIR)/MaximumRangeScaledInteger.o \
	$(OBJDIR)/GeometricPropertiesVariant.o \
	$(OBJDIR)/WhiteBalanceBitField.o \
	$(OBJDIR)/RangeErrorRMSScaledInteger.o \
	$(OBJDIR)/ZoomModesBitField.o \
	$(OBJDIR)/MinimumRangeScaledInteger.o \
	$(OBJDIR)/SensorPositionRefArray.o \
	$(OBJDIR)/MaximumApertureScaledInteger.o \
	$(OBJDIR)/UpdateRateScaledInteger.o \
	$(OBJDIR)/QueryStillImageSensorCapabilitiesList.o \
	$(OBJDIR)/QueryStillImageSensorCapabilitiesRecord.o \
	$(OBJDIR)/GeometricPropertiesSequenceRecord.o \
	$(OBJDIR)/VisualSensorCapabilitiesList.o \
	$(OBJDIR)/BearingValidityEnumeration.o \
	$(OBJDIR)/DataCompressionRefEnumeration.o \
	$(OBJDIR)/QueryVisualSensorCapabilitiesList.o \
	$(OBJDIR)/HorizontalFieldOfViewScaledInteger.o \
	$(OBJDIR)/ConfirmSensorConfigurationVariant.o \
	$(OBJDIR)/DigitalVideoSensorCapabilitesList.o \
	$(OBJDIR)/SupportedFrameSizesBitField.o \
	$(OBJDIR)/QueryRangeSensorConfigurationRecord.o \
	$(OBJDIR)/QueryRangeSensorCompressedDataRecord.o \
	$(OBJDIR)/DigitalVideoSensorConfigurationRecord.o \
	$(OBJDIR)/AnalogVideoSensorErrorRecord.o \
	$(OBJDIR)/MaximumHorizontalFieldOfViewStopAngleScaledInteger.o \
	$(OBJDIR)/AnalogFormatEnumeration.o \
	$(OBJDIR)/VisualSensorConfigurationRecord.o \
	$(OBJDIR)/RangeSensorErrorCodeEnumeration.o \
	$(OBJDIR)/RangeSensorConfigurationRecord.o \
	$(OBJDIR)/RangeSensorDataPointList.o \
	$(OBJDIR)/StillImageSensorConfigurationRecord.o \
	$(OBJDIR)/QueryRangeSensorCapabilitiesRecord.o \
	$(OBJDIR)/RangeSensorCapabilitiesList.o \
	$(OBJDIR)/MaximumFocalLengthScaledInteger.o \
	$(OBJDIR)/TimeStampRefBitField.o \
	$(OBJDIR)/PositionVectorElementScaledInteger.o \
	$(OBJDIR)/MiniumumUpdateRateScaledInteger.o \
	$(OBJDIR)/FocusModesBitField.o \
	$(OBJDIR)/QueryVisualSensorCapabilitiesRecord.o \
	$(OBJDIR)/MaximumShutterSpeedScaledInteger.o \
	$(OBJDIR)/SupportedAnalogFormatsBitField.o \
	$(OBJDIR)/ZoomModeEnumeration.o \
	$(OBJDIR)/QueryVisualSensorConfigurationRecord.o \
	$(OBJDIR)/VisualSensorErrorCodeEnumeration.o \
	$(OBJDIR)/RangeSensorErrorRecord.o \
	$(OBJDIR)/ApertureScaledInteger.o \
	$(OBJDIR)/SensorIdListRefArray.o \
	$(OBJDIR)/QueryStillImageSensorConfigurationRecord.o \
	$(OBJDIR)/RangeSensorDataList.o \
	$(OBJDIR)/QueryRangeSensorCompressedDataList.o \
	$(OBJDIR)/StillImageDataRecord.o \
	$(OBJDIR)/NoGeometricPropertiesVariant.o \
	$(OBJDIR)/FocusModeEnumeration.o \
	$(OBJDIR)/AnalogVideoSensorCapabilitiesList.o \
	$(OBJDIR)/SensorIdRecord.o \
	$(OBJDIR)/AnalogVideoSensorConfigurationListRefArray.o \
	$(OBJDIR)/StillImageSensorConfigurationListRefArray.o \
	$(OBJDIR)/RangeSensorCompressedDataRecord.o \
	$(OBJDIR)/QueryStillImageSensorConfigurationList.o \
	$(OBJDIR)/GeometricPropertiesListRefArray.o \
	$(OBJDIR)/HorizontalFieldOfViewStopAngleScaledInteger.o \
	$(OBJDIR)/ImageStabilizationEnumeration.o \
	$(OBJDIR)/SupportedStatesBitField.o \
	$(OBJDIR)/ExposureModesBitField.o \
	$(OBJDIR)/SensorStateEnumeration.o \
	$(OBJDIR)/DigitalVideoErrorCodeEnumeration.o \
	$(OBJDIR)/SupportedDigitalFormatsBitField.o \
	$(OBJDIR)/MeteringModeEnumeration.o \
	$(OBJDIR)/VerticalFieldOfViewScaledInteger.o \
	$(OBJDIR)/MeteringModesBitField.o \
	$(OBJDIR)/VisualSensorErrorRecord.o \
	$(OBJDIR)/QueryStillImageDataRecord.o \
	$(OBJDIR)/ImagingModesBitField.o \
	$(OBJDIR)/ExposureModeEnumeration.o \
	$(OBJDIR)/VisualSensorCapabilitiesRecord.o \
	$(OBJDIR)/FocusValueScaledInteger.o \
	$(OBJDIR)/FrameSizeRefEnumeration.o \
	$(OBJDIR)/AnalogVideoErrorCodeEnumeration.o \
	$(OBJDIR)/MaximumVerticalFieldOfViewStopAngleScaledInteger.o \
	$(OBJDIR)/BearingScaledInteger.o \
	$(OBJDIR)/VerticalFieldOfViewStartAngleScaledInteger.o \
	$(OBJDIR)/LightSensitivityEnumeration.o \
	$(OBJDIR)/HorizontalFieldOfViewStartAngleScaledInteger.o \
	$(OBJDIR)/RangeSensorDataSeqRecord.o \
	$(OBJDIR)/ManipulatorGeometricPropertiesRecord.o \
	$(OBJDIR)/StillImageFormatEnumeration.o \
	$(OBJDIR)/QueryRangeSensorDataRecord.o \
	$(OBJDIR)/RangeSensorConfigurationListRefArray.o \
	$(OBJDIR)/QueryRangeSensorConfigurationList.o \
	$(OBJDIR)/RangeSensorCompressedDataList.o \
	$(OBJDIR)/MinimumVerticalFieldOfViewStartAngleScaledInteger.o \
	$(OBJDIR)/AnalogVideoSensorConfigurationRecord.o \
	$(OBJDIR)/StillImageSensorList.o \
	$(OBJDIR)/ImageFrameBlob.o \
	$(OBJDIR)/StillImageDataList.o \
	$(OBJDIR)/QueryDigitalVideoConfigurationRecord.o \
	$(OBJDIR)/StreamStateEnumeration.o \
	$(OBJDIR)/MinimumFocalLengthScaledInteger.o \
	$(OBJDIR)/RangeValidityEnumeration.o \
	$(OBJDIR)/CoordinateTransformationSupportedEnumeration.o \
	$(OBJDIR)/InclinationValidityEnumeration.o \
	$(OBJDIR)/RangeSensorCompressedDataVariant.o \
	$(OBJDIR)/ShutterSpeedScaledInteger.o \
	$(OBJDIR)/ImageStablizationEnumeration.o \
	$(OBJDIR)/VerticalFieldOfViewStopAngleScaledInteger.o \
	$(OBJDIR)/UnitQuaternionRefArray.o \
	$(OBJDIR)/RangeScaledInteger.o \
	$(OBJDIR)/RangeSensorDataVariant.o \
	$(OBJDIR)/MinimumShutterSpeedScaledInteger.o \
	$(OBJDIR)/QueryStillImageDataList.o \
	$(OBJDIR)/CompressedDataBlob.o \
	$(OBJDIR)/MinimumHorizontalFieldOfViewStartAngleScaledInteger.o \
	$(OBJDIR)/WhiteBalanceEnumeration.o \
	$(OBJDIR)/FocalLengthScaledInteger.o \
	$(OBJDIR)/InclinationErrorRMSScaledInteger.o \
	$(OBJDIR)/UnitQuaternionElementScaledInteger.o \
	$(OBJDIR)/QueryDigitalVideoConfigurationList.o \
	$(OBJDIR)/DataErrorCodeEnumeration.o \
	$(OBJDIR)/RangeSensorCapabilitiesRecord.o \
	$(OBJDIR)/StillImageSensorErrorRecord.o \
	$(OBJDIR)/LightSensitivityLevelsBitField.o \
	$(OBJDIR)/QueryRangeSensorDataList.o \
	$(OBJDIR)/StillImageSensorCapabilitiesRecord.o \
	$(OBJDIR)/SupportedCompressionBitField.o \
	$(OBJDIR)/ConfirmSensorListRefArray.o \
	$(OBJDIR)/VisualSensorConfigurationListRefArray.o \
	$(OBJDIR)/RequestIdRecRefRecord.o \
	$(OBJDIR)/MinimumApertureScaledInteger.o \
	$(OBJDIR)/DigitalVideoSensorErrorRecord.o \
	$(OBJDIR)/ImagingModeEnumeration.o \
	$(OBJDIR)/QueryVisualSensorConfigurationList.o \
	$(OBJDIR)/ReportCoordinateSystemRefEnumeration.o \
	$(OBJDIR)/ZoomLevelScaledInteger.o \
	$(OBJDIR)/DigitalVideoSensorCapabilitiesRecord.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking openjaus-environment
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning openjaus-environment
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/StillImageSensor.o: ../src/openjaus/environment/StillImageSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensor.o: ../src/openjaus/environment/RangeSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensor.o: ../src/openjaus/environment/AnalogVideoSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensor.o: ../src/openjaus/environment/DigitalVideoSensor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorDefaultLoop.o: ../src/openjaus/environment/Transitions/VisualSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoControlledLoop.o: ../src/openjaus/environment/Transitions/AnalogVideoControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorControlledLoop.o: ../src/openjaus/environment/Transitions/VisualSensorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorControlledLoop.o: ../src/openjaus/environment/Transitions/RangeSensorControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageControlledLoop.o: ../src/openjaus/environment/Transitions/StillImageControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageDefaultLoop.o: ../src/openjaus/environment/Transitions/StillImageDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDefaultLoop.o: ../src/openjaus/environment/Transitions/RangeSensorDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoDefaultLoop.o: ../src/openjaus/environment/Transitions/AnalogVideoDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoControlledLoop.o: ../src/openjaus/environment/Transitions/DigitalVideoControlledLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoDefaultLoop.o: ../src/openjaus/environment/Transitions/DigitalVideoDefaultLoop.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportAnalogVideoSensorCapabilities.o: ../src/openjaus/environment/Triggers/ReportAnalogVideoSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportVisualSensorCapabilities.o: ../src/openjaus/environment/Triggers/ReportVisualSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorCapabilities.o: ../src/openjaus/environment/Triggers/QueryStillImageSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportVisualSensorGeometricProperties.o: ../src/openjaus/environment/Triggers/ReportVisualSensorGeometricProperties.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorConfiguration.o: ../src/openjaus/environment/Triggers/QueryVisualSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmStillImageSensorConfiguration.o: ../src/openjaus/environment/Triggers/ConfirmStillImageSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportDigitalVideoSensorCapabilities.o: ../src/openjaus/environment/Triggers/ReportDigitalVideoSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmAnalogVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/ConfirmAnalogVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ControlDigitalVideoSensorStream.o: ../src/openjaus/environment/Triggers/ControlDigitalVideoSensorStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorGeometricProperties.o: ../src/openjaus/environment/Triggers/QueryVisualSensorGeometricProperties.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportStillImageSensorConfiguration.o: ../src/openjaus/environment/Triggers/ReportStillImageSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorData.o: ../src/openjaus/environment/Triggers/QueryRangeSensorData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetStillImageSensorConfiguration.o: ../src/openjaus/environment/Triggers/SetStillImageSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportRangeSensorGeometricProperties.o: ../src/openjaus/environment/Triggers/ReportRangeSensorGeometricProperties.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoSensorCapabilities.o: ../src/openjaus/environment/Triggers/QueryDigitalVideoSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmDigitalVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/ConfirmDigitalVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportStillImageSensorCapabilities.o: ../src/openjaus/environment/Triggers/ReportStillImageSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/QueryDigitalVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportRangeSensorCompressedData.o: ../src/openjaus/environment/Triggers/ReportRangeSensorCompressedData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportVisualSensorConfiguration.o: ../src/openjaus/environment/Triggers/ReportVisualSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmVisualSensorConfiguration.o: ../src/openjaus/environment/Triggers/ConfirmVisualSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetAnalogVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/SetAnalogVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetRangeSensorConfiguration.o: ../src/openjaus/environment/Triggers/SetRangeSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportDigitalVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/ReportDigitalVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportRangeSensorCapabilities.o: ../src/openjaus/environment/Triggers/ReportRangeSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageData.o: ../src/openjaus/environment/Triggers/QueryStillImageData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetVisualSensorConfiguration.o: ../src/openjaus/environment/Triggers/SetVisualSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorCompressedData.o: ../src/openjaus/environment/Triggers/QueryRangeSensorCompressedData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportRangeSensorConfiguration.o: ../src/openjaus/environment/Triggers/ReportRangeSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QuerySensorGeometricProperties.o: ../src/openjaus/environment/Triggers/QuerySensorGeometricProperties.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportAnalogVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/ReportAnalogVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorCapabilities.o: ../src/openjaus/environment/Triggers/QueryVisualSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SetDigitalVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/SetDigitalVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryAnalogVideoSensorConfiguration.o: ../src/openjaus/environment/Triggers/QueryAnalogVideoSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportStillImageData.o: ../src/openjaus/environment/Triggers/ReportStillImageData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorConfiguration.o: ../src/openjaus/environment/Triggers/QueryStillImageSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorConfiguration.o: ../src/openjaus/environment/Triggers/QueryRangeSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorCapabilities.o: ../src/openjaus/environment/Triggers/QueryRangeSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportRangeSensorData.o: ../src/openjaus/environment/Triggers/ReportRangeSensorData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryAnalogVideoSensorCapabilities.o: ../src/openjaus/environment/Triggers/QueryAnalogVideoSensorCapabilities.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmRangeSensorConfiguration.o: ../src/openjaus/environment/Triggers/ConfirmRangeSensorConfiguration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataErrorRecRefRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataErrorRecRefRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InclinationScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/InclinationScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataPointRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataPointRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BearingErrorRMSScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/BearingErrorRMSScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumUpdateRateScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumUpdateRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/QueryDigitalVideoSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedImageFormatsBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedImageFormatsBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StaticGeometricPropertiesRecord.o: ../src/openjaus/environment/Triggers/Fields/StaticGeometricPropertiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalFormatEnumeration.o: ../src/openjaus/environment/Triggers/Fields/DigitalFormatEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensorConfigurationListRefArray.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoSensorConfigurationListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryDigitalVideoSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/StillImageErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumRangeScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumRangeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GeometricPropertiesVariant.o: ../src/openjaus/environment/Triggers/Fields/GeometricPropertiesVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WhiteBalanceBitField.o: ../src/openjaus/environment/Triggers/Fields/WhiteBalanceBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeErrorRMSScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/RangeErrorRMSScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ZoomModesBitField.o: ../src/openjaus/environment/Triggers/Fields/ZoomModesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumRangeScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumRangeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SensorPositionRefArray.o: ../src/openjaus/environment/Triggers/Fields/SensorPositionRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumApertureScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumApertureScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UpdateRateScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/UpdateRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GeometricPropertiesSequenceRecord.o: ../src/openjaus/environment/Triggers/Fields/GeometricPropertiesSequenceRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BearingValidityEnumeration.o: ../src/openjaus/environment/Triggers/Fields/BearingValidityEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DataCompressionRefEnumeration.o: ../src/openjaus/environment/Triggers/Fields/DataCompressionRefEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/QueryVisualSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HorizontalFieldOfViewScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/HorizontalFieldOfViewScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmSensorConfigurationVariant.o: ../src/openjaus/environment/Triggers/Fields/ConfirmSensorConfigurationVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensorCapabilitesList.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoSensorCapabilitesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedFrameSizesBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedFrameSizesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorCompressedDataRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorCompressedDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensorErrorRecord.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoSensorErrorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumHorizontalFieldOfViewStopAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumHorizontalFieldOfViewStopAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogFormatEnumeration.o: ../src/openjaus/environment/Triggers/Fields/AnalogFormatEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataPointList.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataPointList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/StillImageSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumFocalLengthScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumFocalLengthScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TimeStampRefBitField.o: ../src/openjaus/environment/Triggers/Fields/TimeStampRefBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PositionVectorElementScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/PositionVectorElementScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MiniumumUpdateRateScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MiniumumUpdateRateScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FocusModesBitField.o: ../src/openjaus/environment/Triggers/Fields/FocusModesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryVisualSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumShutterSpeedScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumShutterSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedAnalogFormatsBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedAnalogFormatsBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ZoomModeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ZoomModeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryVisualSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorErrorRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorErrorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ApertureScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/ApertureScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SensorIdListRefArray.o: ../src/openjaus/environment/Triggers/Fields/SensorIdListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataList.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorCompressedDataList.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorCompressedDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageDataRecord.o: ../src/openjaus/environment/Triggers/Fields/StillImageDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NoGeometricPropertiesVariant.o: ../src/openjaus/environment/Triggers/Fields/NoGeometricPropertiesVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FocusModeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/FocusModeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensorCapabilitiesList.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoSensorCapabilitiesList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SensorIdRecord.o: ../src/openjaus/environment/Triggers/Fields/SensorIdRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensorConfigurationListRefArray.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoSensorConfigurationListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageSensorConfigurationListRefArray.o: ../src/openjaus/environment/Triggers/Fields/StillImageSensorConfigurationListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorCompressedDataRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorCompressedDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageSensorConfigurationList.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageSensorConfigurationList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/GeometricPropertiesListRefArray.o: ../src/openjaus/environment/Triggers/Fields/GeometricPropertiesListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HorizontalFieldOfViewStopAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/HorizontalFieldOfViewStopAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImageStabilizationEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ImageStabilizationEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedStatesBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedStatesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExposureModesBitField.o: ../src/openjaus/environment/Triggers/Fields/ExposureModesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SensorStateEnumeration.o: ../src/openjaus/environment/Triggers/Fields/SensorStateEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedDigitalFormatsBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedDigitalFormatsBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MeteringModeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/MeteringModeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VerticalFieldOfViewScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/VerticalFieldOfViewScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MeteringModesBitField.o: ../src/openjaus/environment/Triggers/Fields/MeteringModesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorErrorRecord.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorErrorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageDataRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImagingModesBitField.o: ../src/openjaus/environment/Triggers/Fields/ImagingModesBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ExposureModeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ExposureModeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FocusValueScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/FocusValueScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FrameSizeRefEnumeration.o: ../src/openjaus/environment/Triggers/Fields/FrameSizeRefEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MaximumVerticalFieldOfViewStopAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MaximumVerticalFieldOfViewStopAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BearingScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/BearingScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VerticalFieldOfViewStartAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/VerticalFieldOfViewStartAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LightSensitivityEnumeration.o: ../src/openjaus/environment/Triggers/Fields/LightSensitivityEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HorizontalFieldOfViewStartAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/HorizontalFieldOfViewStartAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataSeqRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataSeqRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ManipulatorGeometricPropertiesRecord.o: ../src/openjaus/environment/Triggers/Fields/ManipulatorGeometricPropertiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageFormatEnumeration.o: ../src/openjaus/environment/Triggers/Fields/StillImageFormatEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorDataRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorDataRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorConfigurationListRefArray.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorConfigurationListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorConfigurationList.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorConfigurationList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorCompressedDataList.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorCompressedDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumVerticalFieldOfViewStartAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumVerticalFieldOfViewStartAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AnalogVideoSensorConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/AnalogVideoSensorConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageSensorList.o: ../src/openjaus/environment/Triggers/Fields/StillImageSensorList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImageFrameBlob.o: ../src/openjaus/environment/Triggers/Fields/ImageFrameBlob.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageDataList.o: ../src/openjaus/environment/Triggers/Fields/StillImageDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoConfigurationRecord.o: ../src/openjaus/environment/Triggers/Fields/QueryDigitalVideoConfigurationRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StreamStateEnumeration.o: ../src/openjaus/environment/Triggers/Fields/StreamStateEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumFocalLengthScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumFocalLengthScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeValidityEnumeration.o: ../src/openjaus/environment/Triggers/Fields/RangeValidityEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CoordinateTransformationSupportedEnumeration.o: ../src/openjaus/environment/Triggers/Fields/CoordinateTransformationSupportedEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InclinationValidityEnumeration.o: ../src/openjaus/environment/Triggers/Fields/InclinationValidityEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorCompressedDataVariant.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorCompressedDataVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ShutterSpeedScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/ShutterSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImageStablizationEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ImageStablizationEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VerticalFieldOfViewStopAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/VerticalFieldOfViewStopAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnitQuaternionRefArray.o: ../src/openjaus/environment/Triggers/Fields/UnitQuaternionRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/RangeScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorDataVariant.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorDataVariant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumShutterSpeedScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumShutterSpeedScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryStillImageDataList.o: ../src/openjaus/environment/Triggers/Fields/QueryStillImageDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CompressedDataBlob.o: ../src/openjaus/environment/Triggers/Fields/CompressedDataBlob.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumHorizontalFieldOfViewStartAngleScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumHorizontalFieldOfViewStartAngleScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WhiteBalanceEnumeration.o: ../src/openjaus/environment/Triggers/Fields/WhiteBalanceEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FocalLengthScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/FocalLengthScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InclinationErrorRMSScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/InclinationErrorRMSScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnitQuaternionElementScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/UnitQuaternionElementScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryDigitalVideoConfigurationList.o: ../src/openjaus/environment/Triggers/Fields/QueryDigitalVideoConfigurationList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DataErrorCodeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/DataErrorCodeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RangeSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/RangeSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageSensorErrorRecord.o: ../src/openjaus/environment/Triggers/Fields/StillImageSensorErrorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/LightSensitivityLevelsBitField.o: ../src/openjaus/environment/Triggers/Fields/LightSensitivityLevelsBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryRangeSensorDataList.o: ../src/openjaus/environment/Triggers/Fields/QueryRangeSensorDataList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StillImageSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/StillImageSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SupportedCompressionBitField.o: ../src/openjaus/environment/Triggers/Fields/SupportedCompressionBitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfirmSensorListRefArray.o: ../src/openjaus/environment/Triggers/Fields/ConfirmSensorListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VisualSensorConfigurationListRefArray.o: ../src/openjaus/environment/Triggers/Fields/VisualSensorConfigurationListRefArray.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RequestIdRecRefRecord.o: ../src/openjaus/environment/Triggers/Fields/RequestIdRecRefRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MinimumApertureScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/MinimumApertureScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensorErrorRecord.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoSensorErrorRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ImagingModeEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ImagingModeEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QueryVisualSensorConfigurationList.o: ../src/openjaus/environment/Triggers/Fields/QueryVisualSensorConfigurationList.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ReportCoordinateSystemRefEnumeration.o: ../src/openjaus/environment/Triggers/Fields/ReportCoordinateSystemRefEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ZoomLevelScaledInteger.o: ../src/openjaus/environment/Triggers/Fields/ZoomLevelScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DigitalVideoSensorCapabilitiesRecord.o: ../src/openjaus/environment/Triggers/Fields/DigitalVideoSensorCapabilitiesRecord.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
