# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug)
  OBJDIR     = Debug/openjaus
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus.so
  DEFINES   += -DDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -Wall -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -shared -L../lib
  LIBS      += -ljson -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = Release/openjaus
  TARGETDIR  = ../lib
  TARGET     = $(TARGETDIR)/libopenjaus.so
  DEFINES   += -DNDEBUG
  INCLUDES  += -I../include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -shared -L../lib
  LIBS      += -ljson -lpthread -lrt
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../lib/libjson.so
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/ControlResponse.o \
	$(OBJDIR)/Connection.o \
	$(OBJDIR)/Action.o \
	$(OBJDIR)/Component.o \
	$(OBJDIR)/MessageCallback.o \
	$(OBJDIR)/Node.o \
	$(OBJDIR)/Event.o \
	$(OBJDIR)/StateMachine.o \
	$(OBJDIR)/Subsystem.o \
	$(OBJDIR)/Transition.o \
	$(OBJDIR)/InternalEvent.o \
	$(OBJDIR)/Service.o \
	$(OBJDIR)/Message.o \
	$(OBJDIR)/TriggerQueue.o \
	$(OBJDIR)/StateMachineRunner.o \
	$(OBJDIR)/SystemTree.o \
	$(OBJDIR)/ActionSet.o \
	$(OBJDIR)/Condition.o \
	$(OBJDIR)/Guard.o \
	$(OBJDIR)/State.o \
	$(OBJDIR)/Trigger.o \
	$(OBJDIR)/MessageReference.o \
	$(OBJDIR)/FieldReference.o \
	$(OBJDIR)/Array.o \
	$(OBJDIR)/EnumerationRange.o \
	$(OBJDIR)/Integer.o \
	$(OBJDIR)/EnumerationItem.o \
	$(OBJDIR)/UnsignedShort.o \
	$(OBJDIR)/Enumeration.o \
	$(OBJDIR)/Unsigned.o \
	$(OBJDIR)/Variant.o \
	$(OBJDIR)/Signed.o \
	$(OBJDIR)/FixedLengthString.o \
	$(OBJDIR)/EnumerationLiteral.o \
	$(OBJDIR)/Record.o \
	$(OBJDIR)/ArrayDimension.o \
	$(OBJDIR)/VariablePointReference.o \
	$(OBJDIR)/Double.o \
	$(OBJDIR)/Blob.o \
	$(OBJDIR)/Message2.o \
	$(OBJDIR)/ScaledInteger.o \
	$(OBJDIR)/VariantItem.o \
	$(OBJDIR)/BitFieldEnumeration.o \
	$(OBJDIR)/VariableLengthString.o \
	$(OBJDIR)/Short.o \
	$(OBJDIR)/Field.o \
	$(OBJDIR)/UnsignedInteger.o \
	$(OBJDIR)/Float.o \
	$(OBJDIR)/ArrayType.o \
	$(OBJDIR)/Byte.o \
	$(OBJDIR)/BitField.o \
	$(OBJDIR)/UnsignedLong.o \
	$(OBJDIR)/ScaledIntegerLimit.o \
	$(OBJDIR)/UnsignedByte.o \
	$(OBJDIR)/Long.o \
	$(OBJDIR)/BitFieldEnumerationValue.o \
	$(OBJDIR)/MessageField.o \
	$(OBJDIR)/BitFieldRange.o \
	$(OBJDIR)/Boolean.o \
	$(OBJDIR)/BlobType.o \
	$(OBJDIR)/BitFieldItem.o \
	$(OBJDIR)/StreamServer.o \
	$(OBJDIR)/PriorityQueue.o \
	$(OBJDIR)/Application.o \
	$(OBJDIR)/Mutex.o \
	$(OBJDIR)/Event2.o \
	$(OBJDIR)/Buffer.o \
	$(OBJDIR)/ScopeLock.o \
	$(OBJDIR)/Thread.o \
	$(OBJDIR)/Logger.o \
	$(OBJDIR)/InetAddress.o \
	$(OBJDIR)/Setting.o \
	$(OBJDIR)/DatagramSocket.o \
	$(OBJDIR)/Socket.o \
	$(OBJDIR)/Timer.o \
	$(OBJDIR)/Condition2.o \
	$(OBJDIR)/StreamSocket.o \
	$(OBJDIR)/Accessable.o \
	$(OBJDIR)/Packet.o \
	$(OBJDIR)/Configuration.o \
	$(OBJDIR)/Exception.o \
	$(OBJDIR)/NetworkInterface.o \
	$(OBJDIR)/Time.o \
	$(OBJDIR)/ZlibCompressor.o \
	$(OBJDIR)/MulticastSocket.o \
	$(OBJDIR)/TransportData.o \
	$(OBJDIR)/Wrapper.o \
	$(OBJDIR)/AddressMap.o \
	$(OBJDIR)/Interface.o \
	$(OBJDIR)/Address.o \
	$(OBJDIR)/Policy.o \
	$(OBJDIR)/CompressedHeader.o \
	$(OBJDIR)/JudpInterface.o \
	$(OBJDIR)/JudpAddress.o \
	$(OBJDIR)/JtcpStream.o \
	$(OBJDIR)/JudpPacket.o \
	$(OBJDIR)/OjudpWrapper.o \
	$(OBJDIR)/JtcpPacket.o \
	$(OBJDIR)/TCPAddress.o \
	$(OBJDIR)/ConfigurationWrapper.o \
	$(OBJDIR)/JtcpInterface.o \
	$(OBJDIR)/JudpLargeMessageBuffer.o \
	$(OBJDIR)/JausWrapper.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking openjaus
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning openjaus
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/ControlResponse.o: ../src/openjaus/model/ControlResponse.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Connection.o: ../src/openjaus/model/Connection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Action.o: ../src/openjaus/model/Action.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Component.o: ../src/openjaus/model/Component.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MessageCallback.o: ../src/openjaus/model/MessageCallback.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Node.o: ../src/openjaus/model/Node.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Event.o: ../src/openjaus/model/Event.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StateMachine.o: ../src/openjaus/model/StateMachine.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Subsystem.o: ../src/openjaus/model/Subsystem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Transition.o: ../src/openjaus/model/Transition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InternalEvent.o: ../src/openjaus/model/InternalEvent.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Service.o: ../src/openjaus/model/Service.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Message.o: ../src/openjaus/model/Message.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TriggerQueue.o: ../src/openjaus/model/TriggerQueue.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StateMachineRunner.o: ../src/openjaus/model/StateMachineRunner.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SystemTree.o: ../src/openjaus/model/SystemTree.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ActionSet.o: ../src/openjaus/model/ActionSet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Condition.o: ../src/openjaus/model/Condition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Guard.o: ../src/openjaus/model/Guard.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/State.o: ../src/openjaus/model/State.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Trigger.o: ../src/openjaus/model/Trigger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MessageReference.o: ../src/openjaus/model/MessageReference.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FieldReference.o: ../src/openjaus/model/fields/FieldReference.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Array.o: ../src/openjaus/model/fields/Array.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EnumerationRange.o: ../src/openjaus/model/fields/EnumerationRange.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Integer.o: ../src/openjaus/model/fields/Integer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EnumerationItem.o: ../src/openjaus/model/fields/EnumerationItem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnsignedShort.o: ../src/openjaus/model/fields/UnsignedShort.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Enumeration.o: ../src/openjaus/model/fields/Enumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Unsigned.o: ../src/openjaus/model/fields/Unsigned.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Variant.o: ../src/openjaus/model/fields/Variant.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Signed.o: ../src/openjaus/model/fields/Signed.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FixedLengthString.o: ../src/openjaus/model/fields/FixedLengthString.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/EnumerationLiteral.o: ../src/openjaus/model/fields/EnumerationLiteral.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Record.o: ../src/openjaus/model/fields/Record.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ArrayDimension.o: ../src/openjaus/model/fields/ArrayDimension.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VariablePointReference.o: ../src/openjaus/model/fields/VariablePointReference.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Double.o: ../src/openjaus/model/fields/Double.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Blob.o: ../src/openjaus/model/fields/Blob.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Message2.o: ../src/openjaus/model/fields/Message.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScaledInteger.o: ../src/openjaus/model/fields/ScaledInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VariantItem.o: ../src/openjaus/model/fields/VariantItem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitFieldEnumeration.o: ../src/openjaus/model/fields/BitFieldEnumeration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/VariableLengthString.o: ../src/openjaus/model/fields/VariableLengthString.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Short.o: ../src/openjaus/model/fields/Short.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Field.o: ../src/openjaus/model/fields/Field.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnsignedInteger.o: ../src/openjaus/model/fields/UnsignedInteger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Float.o: ../src/openjaus/model/fields/Float.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ArrayType.o: ../src/openjaus/model/fields/ArrayType.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Byte.o: ../src/openjaus/model/fields/Byte.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitField.o: ../src/openjaus/model/fields/BitField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnsignedLong.o: ../src/openjaus/model/fields/UnsignedLong.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScaledIntegerLimit.o: ../src/openjaus/model/fields/ScaledIntegerLimit.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/UnsignedByte.o: ../src/openjaus/model/fields/UnsignedByte.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Long.o: ../src/openjaus/model/fields/Long.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitFieldEnumerationValue.o: ../src/openjaus/model/fields/BitFieldEnumerationValue.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MessageField.o: ../src/openjaus/model/fields/MessageField.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitFieldRange.o: ../src/openjaus/model/fields/BitFieldRange.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Boolean.o: ../src/openjaus/model/fields/Boolean.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BlobType.o: ../src/openjaus/model/fields/BlobType.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/BitFieldItem.o: ../src/openjaus/model/fields/BitFieldItem.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StreamServer.o: ../src/openjaus/system/StreamServer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PriorityQueue.o: ../src/openjaus/system/PriorityQueue.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Application.o: ../src/openjaus/system/Application.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Mutex.o: ../src/openjaus/system/Mutex.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Event2.o: ../src/openjaus/system/Event.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Buffer.o: ../src/openjaus/system/Buffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ScopeLock.o: ../src/openjaus/system/ScopeLock.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Thread.o: ../src/openjaus/system/Thread.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Logger.o: ../src/openjaus/system/Logger.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/InetAddress.o: ../src/openjaus/system/InetAddress.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Setting.o: ../src/openjaus/system/Setting.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DatagramSocket.o: ../src/openjaus/system/DatagramSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Socket.o: ../src/openjaus/system/Socket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Timer.o: ../src/openjaus/system/Timer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Condition2.o: ../src/openjaus/system/Condition.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StreamSocket.o: ../src/openjaus/system/StreamSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Accessable.o: ../src/openjaus/system/Accessable.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Packet.o: ../src/openjaus/system/Packet.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Configuration.o: ../src/openjaus/system/Configuration.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Exception.o: ../src/openjaus/system/Exception.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NetworkInterface.o: ../src/openjaus/system/NetworkInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Time.o: ../src/openjaus/system/Time.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ZlibCompressor.o: ../src/openjaus/system/ZlibCompressor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MulticastSocket.o: ../src/openjaus/system/MulticastSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TransportData.o: ../src/openjaus/transport/TransportData.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Wrapper.o: ../src/openjaus/transport/Wrapper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/AddressMap.o: ../src/openjaus/transport/AddressMap.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Interface.o: ../src/openjaus/transport/Interface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Address.o: ../src/openjaus/transport/Address.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Policy.o: ../src/openjaus/transport/Policy.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/CompressedHeader.o: ../src/openjaus/transport/CompressedHeader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JudpInterface.o: ../src/openjaus/transport/AS5669/JudpInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JudpAddress.o: ../src/openjaus/transport/AS5669/JudpAddress.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JtcpStream.o: ../src/openjaus/transport/AS5669/JtcpStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JudpPacket.o: ../src/openjaus/transport/AS5669/JudpPacket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/OjudpWrapper.o: ../src/openjaus/transport/AS5669/OjudpWrapper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JtcpPacket.o: ../src/openjaus/transport/AS5669/JtcpPacket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPAddress.o: ../src/openjaus/transport/AS5669/TCPAddress.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ConfigurationWrapper.o: ../src/openjaus/transport/AS5669/ConfigurationWrapper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JtcpInterface.o: ../src/openjaus/transport/AS5669/JtcpInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JudpLargeMessageBuffer.o: ../src/openjaus/transport/AS5669/JudpLargeMessageBuffer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/JausWrapper.o: ../src/openjaus/transport/AS5669/JausWrapper.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
